### ISSUE TITLE
Mod Suggestion: Impaled

### ISSUE THREAD

**Issue by abilliontrillionstars** [ChloeTax/Hexxytest#26]
Impaled is a small-scope trident expansion mod that adds new trident variants to the game, in less and more power to the vanilla one: 
https://modrinth.com/mod/impaled

(the modrinth page doesn't say much except a slow-paced youtube video, so I'll spare you the watch):
- there's the pitchfork, an earlygame trident that is slowed in water, like non-trident projectiles
trident upgrades:
- the hellfork/soulfork, which does fire damage and **lets the player riptide while on fire** instead of in water
- the elder trident which has **aim-assist/homing properties**
- and the Atlan, which can **accept sword enchantments as well as trident enchants**
these three are made by smithing a trident with an ancient trident (new item, bastion loot), an elder guardian eye (kill an elder with a trident), and a enchanted golden apple, respectively.

the mod also adds an enchantment tweak to Loyalty, allowing player to bind a trident to be extra-loyal to them specifically. they can call the trident like a mjolnir and if another player holds a bound trident of another player, it'll exit that player's inv to return to its owner

**Comment by Twisted-Code** [comment]
This isn't going to be another situation like magic origins where it's poorly documented and ends up breaking things, right? The mention of only having a slow-paced YouTube video on the overview gives me almost the same vibe as documenting on discord.
It sounds pretty cool though (And the alternate riptide might be nice for Enderian) and I'm not seeing any obvious likelihood of a mixin conflict. Fingers crossed?

**Comment by ChloeTax** [comment]
fixed in c8bbc34a6fad48f0cb80dd61fc8bf02ee2ba28be
