### ISSUE TITLE
Mod Update: Hex Ways being on the wrong version

### ISSUE THREAD

**Issue by Stick404** [ChloeTax/Hexxytest#28]
Right now, Hex Ways is on 0.6.1 however the most up-to-date version is 0.7, found here https://modrinth.com/mod/hex-ways/version/wmrYTSyA. It is likely that auto-update missed it because I had 0.6 marked as 6.0 by mistake; however, auto-update should be able to update Hex Ways now.

**Comment by Twisted-Code** [comment]
...Auto update?

**Comment by ChloeTax** [comment]
fixed in 8a2c885c88764382aa855b7b9f9215edd46a4299
