### ISSUE TITLE
Add create track map

### ISSUE THREAD

**Issue by kenbaird13** [ChloeTax/Hexxytest#29]
It would be really nice to get a proper map of the trains on the server, like bluemap does for players..
[Create Track Map](https://modrinth.com/mod/create-track-map)

**Comment by Twisted-Code** [comment]
Suggested priority: [MoSCoW_method](https://en.wikipedia.org/wiki/MoSCoW_method).NICETOHAVE
Mod seems to be reasonably mature, it has existed since at least 1.18. What mixins does it use and  are they likely to conflict with anything?

**Comment by kenbaird13** [comment]
As far as I know, the only mixins it adds are to get the train data and don't actually change anything. Everything else is related to creating and hosting the web page.

**Comment by ChloeTax** [comment]
fixed in b367509fab7ae8fcdfe8b8f443a18df58b3a86e9
