### ISSUE TITLE
Add ToolTipFix for rendering Gloop tooltips + general QoL

### ISSUE THREAD

**Issue by abilliontrillionstars** [ChloeTax/Hexxytest#36]
without ToolTipFix:
![image](https://github.com/user-attachments/assets/687cb233-1cce-456d-9ec5-177f2509ce27)
with ToolTipFix:
![image](https://github.com/user-attachments/assets/7549ab23-93a7-48ba-a567-32aa76b9dc2c)

**Comment by ChloeTax** [comment]
fixed in 4d5e71b1b7b3b999334aed5503ebc0fb5e9ceed0
