### ISSUE TITLE
Mod addition: Hexcellular

### ISSUE THREAD

**Issue by Stick404** [ChloeTax/Hexxytest#38]
Link found here: https://modrinth.com/mod/hexcellular
Since the HexxyCraft++ server has almost all the addons, we should also add in this new one. It adds in global iotas that cost dust to write, but not to read, balancing them out.

**Comment by Twisted-Code** [comment]
Chloe, Ellis, and I had a bit of discussion about this earlier today. I was originally opposed (siding with Ellis who had similar concerns) as it seemed like it might simplify some things too much. However, a bit later I looked at how the project overview describes the mod and it doesn't sound as bad. At a minimum, I like the names of the patterns.
@ChloeTax, I can't speak for Ellis (the other person that objected), but consider my objection CONDITIONALLY withdrawn. I want to see where this goes, but would like if we could try our best to incentivize using the other method of inter~~process~~hex communication. [Law of the Instrument](https://en.wikipedia.org/wiki/Law_of_the_instrument) being what it is, I would still argue that not EVERYTHING should require a truly global variable and it would be nice if there was a way to still limit how many a given player can use. Kind of like how your Sentinel can only have so many foci around it. Sure, Sentinel beds, but that at least adds some complexity to the hex doing it.

**Comment by ChloeTax** [comment]
fixed in 4d5e71b1b7b3b999334aed5503ebc0fb5e9ceed0

**Comment by ChloeTax** [comment]
unfixed in 942be2ff2df026e45c9e942d6614f99eeff719e5

**Comment by Stick404** [comment]
Tested it, and version 1.0.1 launches and works

**Comment by ChloeTax** [comment]
fixed in a135289162e5e27b408ae7ae706b7157a71dddb1
