### ISSUE TITLE
Add Create: Pattern Schematics mod

### ISSUE THREAD

**Issue by abilliontrillionstars** [ChloeTax/Hexxytest#40]
mod adds the ability to make tiled schematics, that is, take a base schematic and copy-paste it in the positioning UI, making a line of copies that can be built in bulk using the schematicannon.

mechanics explained in the first minute or so of this showcase video:
https://youtu.be/DSX_WnU0miE?si=xPQIucSpJqi2KaJl

**Comment by abilliontrillionstars** [comment]
oops, forgot to say, this excels at more easily making mass railway decoration!

**Comment by ChloeTax** [comment]
fixed in 6502ea9a1284348adbcba5840054d58e2ab3c405
