### ISSUE TITLE
Add create big cannons Please

### ISSUE THREAD

**Issue by OakCobra** [ChloeTax/Hexxytest#41]
i would like to 1. produce a cannon factory, 2. mount CC controlled ai autocannons around my base to defend it and 3. be and arms dealer

**Comment by OakCobra** [comment]
https://www.curseforge.com/minecraft/mc-mods/create-big-cannons/files/all?page=1&pageSize=20&version=1.19.2&gameVersionTypeId=4

**Comment by ChloeTax** [comment]
incompatible with immersive portals
