### ISSUE TITLE
add https://modrinth.com/mod/create-origins

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/Hexxytest#43]

**Comment by Twisted-Code** [comment]
Do we really need more origins? It's hard enough being accessible with the existing origins LOL.
Should probably do preliminary testing to make sure there's not any issues like "this ability gives the entire server weakness"

**Comment by ChloeTax** [comment]
create origins doesn't add any origins, it just lets the backtank work with the merling

**Comment by ChloeTax** [comment]
but i do agree we dont need any more origins

**Comment by ChloeTax** [comment]
fixed in e59b83bcbf158770cd20ce215b0c677202d9cd55
