### ISSUE TITLE
update hexical

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/Hexxytest#44]

**Comment by ChloeTax** [comment]
fixed in 91ae8baadbfe9b3c118cfa54c1ad38f9f1f8d449

**Comment by ChloeTax** [comment]
reverted in 02d80bdc2f6d44989b652e2413d500e1007c72b8

**Comment by Stick404** [comment]
Hexical updated, fixed crash due to create https://modrinth.com/mod/hexical/version/1.3.1 (by removing the stuff that crashed with create lol)

**Comment by ChloeTax** [comment]
fixed in 02d80bdc2f6d44989b652e2413d500e1007c72b8
