### ISSUE TITLE
chloeee i need sliiiiiime (bulk item processing is bugged, specifically with turning dough into slime with liquid green mastic resin)

### ISSUE THREAD

**Issue by JesseIsStuckInside** [ChloeTax/Hexxytest#53]
it might've been lime liquid resin actually... point is, it's bugged, no matter how much i blast dough with resin particles it refuses to turn into slime balls. i'm not home and i can't be entirely sure. anyway, my base is at around -1030, ~, -900, go check it out for yourself, it's in the deepslate building with the sawtooth roof

**Comment by Stick404** [comment]
:hexxy:

**Comment by ChloeTax** [comment]
so many mastic recipes are broken...

**Comment by ChloeTax** [comment]
fixed in c7317f7f754ff8b10f8e637fc319ed389c7e20bb
