### ISSUE TITLE
HexStuff out of date (Mod Update)

### ISSUE THREAD

**Issue by Stick404** [ChloeTax/Hexxytest#60]
Hexstuff is out of date, and its most recent version adds in [Display Iotas](https://hexstuff.skye.vg/v/0.2.0/1.0.dev0/en_us/#patterns/display), which are strings, but more expressive. The 0.2.0 version can be found on [Modrinth here](https://modrinth.com/mod/hexstuff/version/0.2.0-fabric)

**Comment by ChloeTax** [comment]
fixed in 00562812390db4fe0ad68fb173611630d81f9b15
