### ISSUE TITLE
HexDebug (mod addition)

### ISSUE THREAD

**Issue by Stick404** [ChloeTax/Hexxytest#61]
Since HexVR has had an update, we can now install HexDebug. However, the [steps](https://github.com/object-Object/HexDebug?tab=readme-ov-file#quilt-kotlin-libraries-version) still need to be followed. (Also, download here https://modrinth.com/mod/hexdebug and here https://modrinth.com/mod/hexvr/version/lwL8TGdL)

**Comment by ChloeTax** [comment]
fixed in 9ae983b84e2c6f87ea0847d3efa92f9d1f9058ae
